server:
  port: 8045
spring:
  application:
    name: microservice-gateway-redis
  # 开启 Gateway 服务注册中心服务发现
  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，# 这个router将以服务名开头的请求路径转发到对应的服务
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #开启小写验证，默认feign根据服务名查找都是用的全大写
  redis:
    host: 47.104.237.163
    port: 6379
    password: root123
    jedis:
          pool:
            max-active: 8
            max-wait: -1ms
            max-idle: 8
            min-idle: 0
            timeout: 6000
    database: 0

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug